// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiverBooks.Books;

#nullable disable

namespace RiverBooks.Books.Data.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20240406044532_InitialBooks")]
    partial class InitialBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Books")
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RiverBooks.Books.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Books", "Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ec5785b5-ae50-4be4-8f58-35190fcbed9f"),
                            Author = "Cormac McCarthy",
                            Price = 9.99m,
                            Title = "Blood Meridian"
                        },
                        new
                        {
                            Id = new Guid("7f9680cf-9130-41c4-8b88-252de10df631"),
                            Author = "Cormac McCarthy",
                            Price = 12.99m,
                            Title = "No Country for Old Men"
                        },
                        new
                        {
                            Id = new Guid("4551182a-5ad4-4d10-9276-ec055719d9f3"),
                            Author = "Cormac McCarthy",
                            Price = 14.99m,
                            Title = "The Road"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
