name: Build and test modular monolith

on:
  push:
    branches: ["main"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Start SQL Server container
        run: docker-compose -f docker-compose.yaml up -d sql

      - name: Test
        run: dotnet test --no-build --verbosity normal
